In [3]:
import cv2
import numpy as np
from datetime import datetime

def mouseHandler(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(event, x, y)
        print(datetime.today())
        filename = str(datetime.today().microsecond)+".jpg"
        cv2.imwrite(filename, img)
        
cv2.namedWindow('Movie')
cv2.setMouseCallback("Movie", mouseHandler)

cap = cv2.VideoCapture("images/Puppies-HD.mp4")

img = None
if cap.isOpened():
    
    print(cap.get(cv2.CAP_PROP_FPS))
    delay = int(1000 / cap.get(cv2.CAP_PROP_FPS))
    while True:
        ret, img = cap.read()
        if ret:
            cv2.imshow("Movie", img)
            if cv2.waitKey(delay) & 0xFF == 27 :
                print("ESC Key pressed")
                break
        else : 
            print("No Frame")
            print(ret, img)
            break

else:
    print("File not opened")
    
cap.release()
cv2.destroyAllWindows()

29.97002997002997
1 467 330
2023-04-21 15:14:02.343647
ESC Key pressed


In [1]:
import cv2

cap = cv2.VideoCapture("images/Puppies-HD.mp4")

if cap.isOpened():
    fourcc = cv2.VideoWriter_fourcc(*'DIVX')
    width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
    height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
    size = (int(width), int(height))
    fps = cap.get(cv2.CAP_PROP_FPS)
    out = cv2.VideoWriter("video.avi", fourcc, fps, size)
    
    delay = int(1000 / cap.get(cv2.CAP_PROP_FPS))
    print(width, height, size, fps, delay)
    
    while True:
        ret, img = cap.read()
        if ret:
            gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
            cv2.imshow("Movie", gray)
            out.write(cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR))
            if cv2.waitKey(delay) & 0xFF== 27:
                print("윈도우 종료")
                break
            
            else:
                print(ret, img)
                break
                
else : 
    print("비디오 안열림")
    
out.release()
cap.release()
cv2.destroyAllWindows()

1280.0 720.0 (1280, 720) 29.97002997002997 33
True [[[ 16  73  51]
  [ 22  79  57]
  [ 21  78  56]
  ...
  [ 10 106  70]
  [ 12 108  72]
  [  6 102  66]]

 [[ 22  79  57]
  [ 28  85  63]
  [ 27  84  62]
  ...
  [ 16 112  76]
  [ 18 114  78]
  [ 12 108  72]]

 [[ 20  77  55]
  [ 26  83  61]
  [ 24  81  59]
  ...
  [ 14 110  74]
  [ 15 111  75]
  [ 10 106  70]]

 ...

 [[ 68 145 126]
  [ 77 154 135]
  [ 62 148 114]
  ...
  [ 83 160 132]
  [ 88 163 135]
  [ 74 149 121]]

 [[ 70 147 128]
  [ 80 157 138]
  [ 65 151 117]
  ...
  [ 86 162 137]
  [ 94 165 141]
  [ 79 150 126]]

 [[ 60 137 118]
  [ 68 145 126]
  [ 55 141 107]
  ...
  [ 75 151 126]
  [ 82 153 129]
  [ 68 139 115]]]


In [6]:
import cv2
import numpy as np

def draw_circle(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        if flags & cv2.EVENT_FLAG_CTRLKEY:
            cv2.rectangle(img, (x,y), (x+20, y+20), (0,0,255), -1)
        else:
            cv2.rectangle(img, (x,y), (x+20, y+20), (0, 255,0), 2)
    elif event == cv2.EVENT_RBUTTONDOWN:
        cv2.circle(img, (x,y), 10, (255,0,0), 2)
    elif event == cv2.EVENT_LBUTTONDBCLK:
        cv2.circle(img, (x,y), 20, (255,0,0), -1)
        
img = np.full((512,512,3), 255, dtype=np.uint8)
cv2.namedWindow('image')
cv2.setMouseCallback('image', draw_circle)

while(1):
    cv2.imshow('image', img)
    if cv2.waitKey(20) & 0xFF == 65:
        break
        
cv2.destroyAllWindows()
    
            

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

AttributeError: module 'cv2' has no attribute 'EVENT_LBUTTONDBCLK'

In [7]:
import cv2
import numpy as np
image = np.full((100, 100, 3), 255, np.uint8)

while(1):
    cv2.imshow("Key test", image)
    key = cv2.waitKey(0)
    print(f'Code: {key}, Char: {chr(key)}')
    if key & 0xFF == 27:
        
cv2.destroyAllWindows()

IndentationError: expected an indented block after 'if' statement on line 9 (931069948.py, line 11)

In [10]:
import cv2
import numpy as np

img = np.full((250,250,3), 255, dtype=np.uint8)

cv2.line(img, (50,10), (200,10), (255,0,0), 1)
cv2.line(img, (50,60), (200,60), (0,255,0), 2)
cv2.line(img, (50,110), (200,110), (0,0,255), 3)
cv2.line(img, (50,160), (200,160), (0,0,0), 4)
cv2.line(img, (50,210), (200,210), (255,0,255), 5)

cv2.imshow('Lines',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import cv2
import numpy as np

img = np.full((250,250,3), 255, dtype=np.uint8)
points = np.array([[[60,60], [100,10], [200,60], [150,100], [100,100]]], dtype=np.int32)

cv2.polylines(img, points, True, (255,0,0), 5)
cv2.polylines(img, points+[0,100], False, (0,0,255), 10)

cv2.imshow('Polylines',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
import cv2
import numpy as np

img = np.full((250,250,3), 255, dtype=np.uint8)

cv2.putText(img, "개발자 BOWSTRING", (10,50), cv2.FONT_ITALIC, 1, (255,0,0))
cv2.putText(img, "One day, One Commit !", (10,150), cv2.FONT_HERSHEY_DUPLEX, 2, (0,0,0))
cv2.putText(img, "This is the way", (10,200), cv2.FONT_HERSHEY_TRIPLEX, 1, (0,0,0))

cv2.imshow('Text', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
import cv2
import numpy as np

img1 = cv2.imread('images/flower1.jpg')
img2 = cv2.imread('images/flower2.jpg')

cv2.imshow('Flower 1', img1)
cv2.imshow('Flower 2', img2)
cv2.imshow('cv2.add', cv2.add(img1,img2))
cv2.imshow('np.add', np.add(img1, img2))
cv2.waitKey(0)
cv2.destroyAllWindows()